[package]
name = "state-m"
version = "0.1.2"
edition = "2024"
description = "The library implements convenient state distribution and management mechanisms, facilitating collaborative work between components."
repository = "https://github.com/xiongxiong/state-m"
authors = ["WonderBear<ximengwuheng@163.com>"]
keywords = ["state", "machine", "subscribe"]
license = "MIT"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
dashmap = "6.2.1"
thiserror = "2.0.18"
tokio = {version = "1.52.3", features = ["full"]}
tokio-util = "0.7.18"
tracing = "0.1.44"

[[test]]
name = "test"
path = "tests/test.rs"
