[package]
name = "state-m"
version = "0.8.4"
edition = "2024"
description = "The library implements convenient state distribution and management mechanisms, facilitating collaborative work between components."
repository = "https://github.com/xiongxiong/state-m"
authors = ["WonderBear<ximengwuheng@163.com>"]
keywords = ["state", "machine", "subscribe"]
license = "MIT"

[dependencies]
anyhow = "1.0"
arc-swap = "1.9"
async-trait = "0.1"
chrono = "0.4"
dashmap = "6.2"
derivative = "2.2"
downcast-rs = "2.0"
itertools = "0.15"
state-m-macro = "0.2"
thiserror = "2.0"
tokio = { version = "1.52", features = ["macros", "rt", "sync"] }
tokio-util = "0.7"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = "0.3"
tokio = { version = "1.52", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }

[features]
default = []

[[test]]
name = "test"
path = "tests/test.rs"

[[test]]
name = "expand"
path = "tests/expand.rs"
