[package]
name = "state-m-macro"
version = "0.2.3"
edition = "2024"
description = "The library implements convenient macros for state-m crate."
repository = "https://github.com/xiongxiong/state-m-macro"
authors = ["WonderBear<ximengwuheng@163.com>"]
keywords = ["state-m", "macro", "state", "machine"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
itertools = "0.15"
macro_tools = "0.88"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
